// <auto-generated />
namespace OfficeEmployeeVisitorTrackingSysytem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addAdminCompanyInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAdminCompanyInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201810030908453_addAdminCompanyInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
